#!/usr/bin/python3
from sys import argv
from math import sqrt

def factor():
    """
    Factorize many numbers possible into product of two smaller numbers.
"""
    with open(argv[1]) as f:
        for line in f:
            n = int(line)
            print("{:d}=".format(n), end="")
            if n % 2 == 0:
                print("{}*2".format(n//2))
                continue
            s = int(sqrt(n))
            if s % 2 == 0:
                s += 1
            for i in range(3, s + 1, 2):
                if n % i == 0:
                    print("{}*{}".format(i, n//i))
                    break
            if n % i != 0:
                print("{}={}*1".format(n, n))


factor()
