#!/usr/bin/python3
if __name__ == "__main__":
    from sys import argv
    from math import sqrt

    def factors():
        """Factorize many numbers possible into product of two smaller numbers
        Output format: n=p*q
        one factorization per line
        p and q don’t have to be prime numbers
        assume that all lines will be valid natural numbers greater than 1
        one factorization per line
        """
        with open(argv[1]) as f:
            for line in f:
                n = int(line)
                p = 2
                q = n
                while p <= sqrt(n):
                    if n % p == 0:
                        q = n // p
                        print("{}={}*{}".format(n, p, q))
                        break
                    p += 1
                if p > sqrt(n):
                    print("{}={}*{}".format(n, p, q))

    factors()
